import { darkTokens } from './dark';
import type { Theme } from './types';

/**
 * 浅色的令牌。
 *
 * 界面部分照 WebStorm 的 Islands Light 实测值（chrome e9eaee、面板与编辑器 ffffff）与 Light.icls 里的
 * 文字／分隔线／选区（080808 / 8c8c8c / ebecf0 / a6d2ff / f5f8fe / aeb3c2）铺出来；编辑器与语法全部照 Light.icls。
 * 查看器保持深底中性灰：图片区域不跟主题。
 *
 * 这里不覆盖 --el-* 色阶——Element Plus 自带的浅色默认就是浅色下合适的，只有品牌主色靠 CSS 里的映射跟着走。
 */
export const light: Theme<typeof darkTokens> = {
  tokens: {
    "--app-space-2": "2px",
    "--app-space-4": "4px",
    "--app-space-6": "6px",
    "--app-space-8": "8px",
    "--app-space-10": "10px",
    "--app-space-12": "12px",
    "--app-space-16": "16px",
    "--app-space-20": "20px",
    "--app-space-24": "24px",
    "--app-space-32": "32px",
    "--app-radius-2": "2px",
    "--app-radius-4": "4px",
    "--app-radius-6": "6px",
    "--app-radius-8": "8px",
    "--app-font-xs": "11px",
    "--app-font-sm": "12px",
    "--app-font-base": "13px",
    "--app-font-md": "14px",
    "--app-font-lg": "16px",
    "--app-bg-page": "#ffffff",
    "--app-bg-surface": "#ffffff",
    "--app-bg-header": "#e9eaee",
    "--app-bg-hover": "#f2f3f5",
    "--app-bg-active": "#e9eaee",
    "--app-bg-track": "#ebecf0",
    "--app-bg-disabled": "#f7f8f9",
    "--app-border": "#ebecf0",
    "--app-border-subtle": "#f2f3f5",
    "--app-border-strong": "#d9dce1",
    "--app-border-hover": "#c8ccd3",
    "--app-text-primary": "#080808",
    "--app-text-regular": "#27282b",
    "--app-text-secondary": "#5c5f66",
    "--app-text-muted": "#8c8c8c",
    "--app-text-disabled": "#a8adb5",
    "--app-text-soft": "#6f737a",
    "--app-text-faint": "#b9bdc5",
    "--app-text-ghost": "#d0d3d9",
    "--app-primary": "#3871e1",
    "--app-primary-hover": "#2f65c9",
    "--app-on-primary": "#ffffff",
    "--app-success": "#2f7a4c",
    "--app-success-hover": "#276a41",
    "--app-warning": "#c79a2b",
    "--app-danger": "#c75458",
    "--app-danger-hover": "#b34b4f",
    "--app-info": "#6e737a",
    "--app-tag-success-bg": "#e6f4ea",
    "--app-tag-success-border": "#a8d8b9",
    "--app-tag-success-text": "#1f7a45",
    "--app-tag-danger-bg": "#fdecec",
    "--app-tag-danger-border": "#f0b9bb",
    "--app-tag-danger-text": "#b93b40",
    "--app-tag-warning-bg": "#fdf6e3",
    "--app-tag-warning-border": "#e8d29a",
    "--app-tag-warning-text": "#8a6d15",
    "--app-tag-info-bg": "#f2f3f5",
    "--app-tag-info-border": "#d9dce1",
    "--app-tag-info-text": "#5c5f66",
    "--app-tag-primary-bg": "#e8effc",
    "--app-tag-primary-border": "#b6cbf3",
    "--app-tag-primary-text": "#2f65c9",
    "--app-tag-similar-bg": "#e3f6fa",
    "--app-tag-similar-border": "#a5dce9",
    "--app-tag-similar-text": "#0f7d94",
    "--app-viewer-bg": "#1e1f22",
    "--app-viewer-surface": "#2b2d30",
    "--app-viewer-text": "#c8cad0",
    "--app-viewer-text-dim": "rgba(255, 255, 255, 0.5)",
    "--app-viewer-text-bright": "rgba(255, 255, 255, 0.9)",
    "--app-viewer-fade": "rgba(43, 45, 48, 0)",
    "--app-accent": "#2f6fe0",
    "--app-bg-selected": "#e9eaee",
    "--app-bg-highlight": "#e8effc",
    "--app-border-highlight": "#b6cbf3",
    "--app-danger-tint": "rgba(199, 84, 88, 0.12)",
    "--app-overlay-scrim": "rgba(0, 0, 0, 0.45)",
    "--app-mask": "rgba(255, 255, 255, 0.7)",
    "--app-shadow-dialog": "0 16px 48px rgba(0, 0, 0, 0.18)",
    "--app-shadow-popup": "0 8px 24px rgba(0, 0, 0, 0.18)",
    "--app-shadow-tile": "0 10px 26px rgba(0, 0, 0, 0.3)",
    "--app-shadow-tile-hover": "0 12px 30px rgba(0, 0, 0, 0.35)",
    "--app-shadow-viewer": "0 4px 20px rgba(0, 0, 0, 0.7)",
    "--app-shadow-viewer-thumb": "0 2px 12px rgba(0, 0, 0, 0.4)",
  },
  monaco: {
    base: 'vs',
    rules: [
      { token: 'comment', foreground: '8c8c8c' },
      { token: 'keyword', foreground: '0033b3' },
      { token: 'string', foreground: '067d17' },
      { token: 'number', foreground: '1750eb' },
      { token: 'constant', foreground: '871094' },
      { token: 'function', foreground: '00627a' },
      { token: 'type', foreground: '00627a' },
      { token: 'operator', foreground: '080808' },
      { token: 'delimiter', foreground: '080808' },
    ],
    colors: {
      'editor.background': '#ffffff',
      'editorGutter.background': '#ffffff',
      'editor.lineHighlightBackground': '#f5f8fe',
      'editorLineNumber.foreground': '#aeb3c2',
      'editorLineNumber.activeForeground': '#080808',
      'editorIndentGuide.background1': '#ebecf0',
      'editor.selectionBackground': '#a6d2ff',
      'editorCursor.foreground': '#080808',
    },
  },
};
